%YAML:1.0
CameraInfo:
  -
    Name: usbcam2fay21_l
    DevID: "http://aypi2:8080/?action=stream&dummy=file.mjpg"
    Width: 320
    Height: 240
    PixelFormat: MJPG
    NRotate90: 0
    Rectification: 1
    Alpha: 0.8
    K: !!opencv-matrix
      rows: 3
      cols: 3
      dt: d
      data: [ 2.9626599933569219e+02, 0., 1.6184603192794432e+02, 0.,
          2.9626599933569219e+02, 1.2062472517136455e+02, 0., 0., 1. ]
    D: !!opencv-matrix
      rows: 1
      cols: 5
      dt: d
      data: [ -9.5718286674593955e-01, 5.5100676290063433e-01, 0., 0., 0. ]
    R: !!opencv-matrix
      rows: 3
      cols: 3
      dt: d
      data: [ 1.0, 0.0, 0.0,  0.0, 1.0, 0.0,  0.0, 0.0, 1.0 ]
  -
    Name: usbcam2fay21_r
    DevID: "http://aypi2:8081/?action=stream&dummy=file.mjpg"
    Width: 320
    Height: 240
    PixelFormat: MJPG
    NRotate90: 0
    Rectification: 1
    Alpha: 0.8
    K: !!opencv-matrix
      rows: 3
      cols: 3
      dt: d
      data: [ 2.9626599933569219e+02, 0., 1.6184603192794432e+02, 0.,
          2.9626599933569219e+02, 1.2062472517136455e+02, 0., 0., 1. ]
    D: !!opencv-matrix
      rows: 1
      cols: 5
      dt: d
      data: [ -9.5718286674593955e-01, 5.5100676290063433e-01, 0., 0., 0. ]
    R: !!opencv-matrix
      rows: 3
      cols: 3
      dt: d
      data: [ 1.0, 0.0, 0.0,  0.0, 1.0, 0.0,  0.0, 0.0, 1.0 ]

BlobTracker:
  -
    # SBDParams_filterByColor: 0
    # SBDParams_blobColor: 0
    # SBDParams_minThreshold : 30
    # SBDParams_maxThreshold : 200
    # SBDParams_filterByArea : true
    # SBDParams_minArea : 40
    # SBDParams_filterByCircularity : true
    # SBDParams_minCircularity : 0.10
    # SBDParams_filterByConvexity : true
    # SBDParams_minConvexity : 0.87
    # SBDParams_filterByInertia : true
    # SBDParams_minInertiaRatio : 0.01
    DistNeighbor: 20.0
    DistMin: 0.0
    DistMax: 20.0
    DSMin: -1.0
    DSMax: 10.0
    DistMinCalib: 3.0
    DistMaxCalib: 20.0
    DSMinCalib: -1.0
    DSMaxCalib: 10.0
    DSEmp: 4.0
    DPEmp: 10.0
    NCalibPoints: 20
  -
    DistNeighbor: 20.0
    DistMin: 0.0
    DistMax: 20.0
    DSMin: -1.0
    DSMax: 10.0
    DistMinCalib: 3.0
    DistMaxCalib: 20.0
    DSMinCalib: -1.0
    DSMaxCalib: 10.0
    DSEmp: 4.0
    DPEmp: 10.0
    NCalibPoints: 20

StereoInfo:{}
